react-component/dialog

src/Dialog.jsx

close dialog on ESC

---

README.md
package.json
tests/index.spec.js

rc-animate@1.x 和 rc-align@1.x 都不兼容 react@0.14

upgrade demo, tests and deps for react@0.14.x

---

examples/ant-design.js
examples/bootstrap.js
package.json
src/Dialog.jsx
src/DialogWrap.jsx
tests/index.spec.js

ref: https://github.com/ant-design/ant-design/issues/941
```js
onClose(e) {
console.log(e.target);
}
```
可以在受控模式下判断 `e.target`。

Feature on close event

---

assets/bootstrap.less
assets/bootstrap/Mask.less
assets/bootstrap/body.less
assets/index.less
assets/index/Mask.less
assets/index/body.less
src/DOMWrap.jsx
src/Dialog.jsx

Avoid body scrolling when dialog open

---

src/Modal.tsx

On iOS, the modal is still restricted by what's specified in your app's Info.plist's UISupportedInterfaceOrientations field. [react native doc modal](http://facebook.github.io/react-native/releases/0.44/docs/modal.html), so need add flowing code to support supportedOrientations,
```jsx
<Modal
visible={true}
supportedOrientations={['portrait', 'landscape']}  // 使ios上支持横屏显示
>
</Modal>
```
see [issue](https://github.com/facebook/react-native/issues/11036)

add ios orientations support

---

README.md
src/Dialog.tsx
src/IDialogPropTypes.tsx
tests/index.js

Adding destroyOnHide to Dialog unmount child components
Addresses #22 && [Add [destroyOnHide] to Modal #8494](https://github.com/ant-design/ant-design/issues/8494)

Add option destroyOnHide

---

assets/index/Dialog.less
tests/index.js

the footer container should align with `title` and `body`, but actually users have to set extra padding style for the container manually at present.

fix footer padding style

---

README.md
examples/ant-design.tsx
package.json
src/Dialog.tsx
src/DialogWrap.tsx
src/IDialogPropTypes.tsx
tests/index.js

Add forceRender props.
ref #93 and https://github.com/ant-design/ant-design/issues/12503

add forceRender props for Dialog component.

---

src/LazyRenderBox.tsx

forceRender 不渲染到dom上
> index.js:2177 Warning: React does not recognize the `forceRender` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `forcerender` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

fix forceRender dom render warning

---

examples/multiple-Portal.tsx
package.json
src/Dialog.tsx

Ref: https://github.com/react-component/dialog/pull/153#issuecomment-544879586

fix: typescript compile error

---

src/Dialog.tsx

Fixed https://github.com/ant-design/ant-design/issues/19393

fix: IE browser does not set overflow style

---

src/Dialog.tsx
tests/index.js

Root node was previously an empty <div>. It now gets its own (prefixed) class name, which is by default "rc-dialog-root". I need this for be able to reliably grab those root nodes in DOM (force stacking context for correct mask rendering with nested modals in ant-design)
Note: I first chose "<prefix>-container", but since "container" is already used as a term (e.g. DialogWrap), i opted for "<prefix>-root"

feat: class name for root node

---

examples/bootstrap.tsx
package.json

Update bootstrap version to fix the error `Module build failed: ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin`.
Fixes #99, and I also got the same error when running development preview via `npm start`. That is also fixes by this PR.
I also added Bootstrap-styled components (buttons) to illustrate the Bootstrap theming (and to test if example now correctly includes Bootstrap CSS)

fix: svg-sprite-loader exception for "npm start" and bootstrap example

---

examples/draggable.tsx
package.json
src/Dialog.tsx
src/IDialogPropTypes.tsx
tests/index.spec.js

https://github.com/ant-design/ant-design/issues/16613
https://github.com/ant-design/ant-design/issues/13230
https://github.com/ant-design/ant-design/issues/4617
https://github.com/ant-design/ant-design/issues/374
添加Modal组件框的body可自定义。这样可以方便的重写body, 来进行自定义拖拽，或者最大化，最小化等功能
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |     添加一个modalRender 属性     |
> 请自检并全部勾选上

fate: add modalRender

---

package.json

https://github.com/react-component/image/pull/25 导入出错。

fix: remove typing from package.json

---

src/Dialog.tsx

close ant-design/ant-design#26528

fix: page scroll position will jump after dialog is closed

---

examples/ant-design.tsx
package.json
src/Dialog/Content.tsx
src/Dialog/index.tsx
tests/portal.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/27080
resolve https://github.com/ant-design/ant-design/issues/27084

fix: Portal event bubble

---

src/DialogWrap.tsx
tests/index.spec.js

resolve https://github.com/ant-design/ant-design/issues/27108

fix: Dialog should not auto destroy

---

examples/bootstrap.tsx
src/Dialog/Content/MemoChildren.tsx
src/Dialog/Content/index.tsx
tests/index.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/27372

chore: Should not re-render when dialog is invisible

---

src/Dialog/Content/index.tsx
src/Dialog/index.tsx
tests/portal.spec.tsx

ref https://github.com/ant-design/ant-design/issues/27391

fix: dialog dont close when mouseDown in content and mouseUp in wrapper

---

src/Dialog/Content/index.tsx
src/Dialog/index.tsx

fix https://github.com/ant-design/ant-design/issues/28353
fix https://github.com/ant-design/ant-design/issues/28399
在 https://github.com/ant-design/ant-design/issues/28353 中，点击 label 中的元素，label 会连续触发两次点击事件，冒泡到父级弹窗的时候，由于父子弹窗没有包含的关系，就会触发父级的关闭事件。
在 https://github.com/ant-design/ant-design/issues/28399 是因为在下拉框中的触发点击事件，冒泡了上来，但是下拉框和弹窗没有包含关系，也会触发关闭事件。
https://github.com/react-component/dialog/blob/4c3b871feb8549fb46413bc7be7460da8a779e8a/src%2FDialog%2Findex.tsx#L115 这里的逻辑其实就是只要不是点击的内容就触发关闭，在弹窗中 wrap 是撑满屏幕，不点击内容就是点击 wrap 本身，刚好规避了上述两种特殊情况
@zombieJ 评估一下，有没有副作用。

fix: trigger close only when click wrap itself

---

src/Dialog/index.tsx
tests/index.spec.tsx

close https://github.com/ant-design/ant-design/issues/29009

fix: afterClose unexpected call when mount dialog

---

src/Dialog/index.tsx

通过 cypress 编写测试。页面中存在多个 Drawer 时，通过传递不同的 data-test-id 属性给对应 Drawer 组件，然后通过 data-test-id 可以准确获得对应的 DOM 元素。但是 Modal 组件将 data-test-id 给丢弃了。并没有在 DOM 元素上设置。从而造成不能准确地获取对应的 DOM 元素。
fix https://github.com/ant-design/ant-design/issues/30716

feat: support data-*

---

src/Dialog/Mask.tsx
src/Dialog/index.tsx
src/IDialogPropTypes.tsx
tests/__snapshots__/index.spec.tsx.snap
tests/index.spec.tsx

[v5改版](https://github.com/ant-design/ant-design/issues/34087) `IMAGE`组件在修改为cssinjs中,涉及到改组件,需要在顶层添加`rootClassName`api

feat: add rootClassName

---

package.json
src/Dialog/index.tsx
src/util.ts
tests/__snapshots__/index.spec.tsx.snap
tests/index.spec.tsx

修复 Dialog 跨 React 版本的 snapshot 问题
ref https://github.com/ant-design/ant-design/pull/35026

refactor: Use useId to sync snapshot in test env

---

src/Dialog/Content/index.tsx
src/Dialog/index.tsx
tests/__snapshots__/index.spec.tsx.snap

Dialog's boundaries are not communicated because of improper structure.
When this is not done, it is unclear to screen readers when they are leaving or entering a dialog when using the virtual cursor.
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html
`Role=document` does not need to be used. `role=dialog` should be moved to where your `role=document` was.

Fixes accessibility issue created by incorrect dialog role

---

src/Dialog/Mask.tsx

bind ref to CSSMotion, avoid rc-motion call findDOMNode，need RC release new version about this [pr](https://github.com/react-component/motion/pull/17)

feat: CSSMotion bind ref, avoid rc-motion call findDOMNode

---

src/Dialog/index.tsx
src/IDialogPropTypes.tsx
tests/index.spec.tsx

close https://github.com/ant-design/ant-design/issues/40810
close https://github.com/react-component/dialog/pull/251

feat: add afterOpenChange prop

---

.husky/pre-commit
src/Dialog/Content/Panel.tsx
src/DialogWrap.tsx
src/IDialogPropTypes.tsx
src/context.ts
tests/ref.spec.tsx

添加 `panelRef` 以供 antd Modal 可以获取弹出窗口的 ref。

feat: support panelRef

---

src/Dialog/Content/Panel.tsx
src/IDialogPropTypes.tsx
tests/index.spec.tsx

- https://github.com/ant-design/ant-design/discussions/47188

feat: Dialog support aria-* in closable

---

src/Dialog/Content/index.tsx

This updates the mousePostion check for the transform-origin calculation.
In some rare cases, e.g. in a TestEnvironment (react-testing-library with Jest) the mousePosition can look like this:
```js
{
x: undefined,
y : undefined
}
```
which leads to `transform-origin: NaNpx NaNpx;` in the element itself.
This check fixes this issue.

Update mousePosition check

---

README.md

classnames and styles 目前都是支持这六个的，补充缺失的content，按照ts类型的顺序重新排序了文档中的顺序，方便检查。

docs(type): supplement classnames and styles

---

package.json
src/Dialog/Content/Panel.tsx
src/Dialog/index.tsx
tests/index.spec.tsx
tests/setup.js

Same patch as https://github.com/react-component/dialog/pull/430 but for antd@4.x
close https://github.com/ant-design/ant-design/issues/50170

fix(antd@4.x): prevent scroll when modal container and sentinel get focused

---

src/Dialog/Content/Panel.tsx
tests/__snapshots__/index.spec.tsx.snap

close https://github.com/ant-design/ant-design/issues/50170
Blocked aria-hidden on a `<div>` element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. `<div tabindex=​"0" aria-hidden=​"true" style=​"width:​ 0px;​ height:​ 0px;​ overflow:​ hidden;​ outline:​ none;​">​</div>`
看了下 MUI 也没有加 `aria-hidden`。​

fix: Avoid using aria-hidden on a focused element
