- assets/index/Dialog.less
- examples/ant-design.js
- src/Dialog.jsx
- src/DialogWrap.jsx
支持新的动画方式。
https://t.alipayobjects.com/images/rmsweb/T1br0gXghtXXXXXXXX.webm
> Add mousePosition prop for new ant design animation

- assets/index/Dialog.less
- src/Dialog.jsx
- tests/index.spec.js
将 close 从 header 中拿出来，因为存在没有 header 但是有 close 的场景。
> Make header and close x isolate

- src/Dialog.tsx
See https://github.com/ant-design/ant-design/issues/4120
> Uncaught Error: must set key for <rc-animate> children - fix

- src/Dialog.tsx
fix https://github.com/ant-design/ant-design/issues/3805
> remove style setting when unmount

- examples/ant-design.tsx
- examples/bootstrap.tsx
- src/Dialog.tsx
- src/DialogWrap.tsx
- src/IDialogPropTypes.tsx
- src/LazyRenderBox.tsx
- src/Modal.tsx
according to https://github.com/ant-design/ant-design/issues/4475#issuecomment-273064508
> fix scrolling effect

- package.json
- tests/index.js
ref: 
https://github.com/ant-design/ant-design-mobile/issues/959
> feat: upgrade rc-util to 4.x

- README.md
- src/DialogWrap.tsx
- tests/index.js
ref: https://github.com/ant-design/ant-design/issues/5479
> Feat getContainer

- examples/ant-design.tsx
- examples/bootstrap.tsx
- examples/react-native/demo.tsx
- package.json
- src/Dialog.tsx
- src/DialogWrap.tsx
- src/LazyRenderBox.tsx
- src/Modal.tsx
- tests/index.js
same as https://github.com/react-component/dialog/pull/56
> Fix prop-types and create-react-class warning

- .gitignore
- package.json
https://github.com/react-component/react-component.github.io/issues/12
> feat: add es

- package.json
- src/Dialog.tsx
- src/LazyRenderBox.tsx
- typings/custom.d.ts
> remove object-assign

- src/Dialog.tsx
Fix for issue: https://github.com/react-component/dialog/issues/83
> Fixed an issue with ref as string due new restriction in React 16

- src/DialogWrap.tsx
- tests/index.js
那一大段注释不知道是否清晰...觉得没有必要就删掉
issue #10656 : https://github.com/ant-design/ant-design/issues/10656
> fix issue #10656

- src/Dialog.tsx
stopPropagation
fix ant-design/ant-design#11394
> 嵌套Modal时 Esc应逐层响应事件

- README.md
- examples/ant-design.tsx
- src/Dialog.tsx
- src/IDialogPropTypes.tsx
- tests/index.js
> support custom close icon.

- src/Dialog.tsx
- tests/index.js
To fixed this [issue](https://github.com/react-component/dialog/issues/63). Pls kindly review it.
> fix 'Shift-Tabbing leads focus escape from Dialog to outside.'

- src/Dialog.tsx
close ant-design/ant-design#17027 and maybe https://github.com/ant-design/ant-design/issues/9380 and https://github.com/ant-design/ant-design/issues/6166
solution: https://stackoverflow.com/a/13532017/3040605
> fix: 🐛 Fix close button auto submit when press enter in IE

- examples/ant-design.tsx
- examples/bootstrap.tsx
- examples/multiple-Portal.tsx
- package.json
- src/Dialog.tsx
- src/DialogWrap.tsx
- src/IDialogPropTypes.tsx
- tests/index.js
与 drawer 同用一个 portal。。
#123 在这里没问题。。那个关了吧。。
https://github.com/ant-design/ant-design/issues/17323
> Portal wrapper

- src/Dialog.tsx
https://github.com/ant-design/ant-design/issues/9792
> refactor: remove componentWillMount

- src/Dialog.tsx
- src/LazyRenderBox.tsx
forceRender 只是会 render 但是 props 更新不会触发渲染。
> forceRender should anything render

- src/Dialog.tsx
Fixed https://github.com/ant-design/ant-design/issues/19332
> fix: removeScrollingEffect error cause by multiple dialog cancel

- examples/ant-design.tsx
- src/Dialog.tsx
- tests/index.js
Fixed https://github.com/ant-design/ant-design/issues/19340
> fix: multiple Dialog change visible abnormal

- src/Dialog.tsx
Fixes https://github.com/ant-design/ant-design/issues/19676
> fix: switchScrollingEffect not trigger

- README.md
- examples/ant-design.tsx
- src/Dialog.tsx
- src/IDialogPropTypes.tsx
Fixes https://github.com/react-component/dialog/issues/95
Fixes https://github.com/ant-design/ant-design/issues/19771
> feat: add disableFocus prop

- package.json
- src/Dialog.tsx
- tests/index.js
Ref: https://github.com/react-component/util/pull/65
> refactor: use rc-util Portal switchScrollingEffect

- src/DialogWrap.tsx
- https://github.com/react-component/image/pull/25#issuecomment-685251167
> fix: add displayName

- src/Dialog/Content/MemoChildren.tsx
- src/Dialog/Content/index.tsx
- tests/index.spec.tsx
> fix: Dialog should keep refresh when `forceRender` provided

- src/Dialog/index.tsx
Related
https://github.com/ant-design/ant-design/pull/28687#issuecomment-755326801
> improve: ScrollLocker call related

- docs/demo/pure.md
- docs/examples/pure.tsx
- src/Dialog/Content/Panel.tsx
- src/Dialog/Content/index.tsx
- src/Dialog/index.tsx
- src/index.ts
ref https://github.com/ant-design/ant-design/issues/34087
> feat: export dialog panel

- package.json
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62793#issuecomment-1285167695
> fix: error TS2688: Cannot find type definition file for keyv

- src/Dialog/index.tsx
ref #292
close https://github.com/ant-design/ant-design/issues/36911
close https://github.com/ant-design/ant-design/issues/38232
close #292
cc @ousiri 看看是不是这样就够了？
> fix: Dialog start with mouse pos

- src/Dialog/index.tsx
- tests/index.spec.tsx
close #280
https://github.com/ant-design/ant-design/issues/32923
Thx to @ElvisUpUp
> fix: focusTriggerAfterClose not working

- docs/examples/multiple-Portal.tsx
fix the issue in the demo where the p element covers the close button, resulting in invalid clicks
> fix: fix the issue in the demo where the p element covers the close button, resulting in invalid clicks

- src/Dialog/Content/Panel.tsx
- src/Dialog/index.tsx
close https://github.com/ant-design/ant-design/issues/48699
> fix: prevent scroll when modal container and sentinel get focused

- src/Dialog/Content/index.tsx
- tests/index.spec.tsx
ref https://github.com/react-component/dialog/pull/426
> fix: transform support one is 0
